interface HouseInfo {
    "id": number,
    /** 展示名称 */
    "listing_name": string,
    "first_upload_at": string,
    "pricing": number,
    "squaremeter": number,
    "downpayment"?: any,
    "floor"?: any,
    "total_floor": number,
    "dict_house_id": number,
    "room_structure"?: any,
    "ladder_ration"?: any,
    "heating_type"?: any,
    "house_duration"?: any,
    "property_right"?: any,
    "mortgage"?: any,
    "usage_area": number,
    "floor_level": number,
    "facing_type": number,
    "decoration_type"?: any,
    "building_type"?: any,
    "built_year": string,
    "city_name": string,
    "city_code": string,
    "neighborhood_name": string,
    "neighborhood_source_code": string,
    "floor_plan_room": number,
    "floor_plan_hall": number,
    "floor_plan_bath": number,
    "floor_plan_kitchen": number,
    "house_type": number,
    "layout_type": number,
    "last_publish_time": string,
    "ownership"?: any,
    "right_property"?: any,
    "property_management_type": number,
    "elevator"?: any,
    "house_status": number,
    "online_house_status": number,
    "created_at":string,
    "updated_at":string,
    "data_source_id": number,
    "offline_code": string,
    "source_code": string,
    "start_version": number,
    "last_version": number,
    "crawl_id": number,
    "task_id": number,
    "house_card"?: any,
    "online_neighborhood_id": number,
    "online_city_id": number,
    "online_district_id": number,
    "online_area_id": number,
    "property_only"?: any,
    "property_certificate_period"?: any
}
